
---
title: "Basic Usage"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Basic Usage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

##### Load the package and data
```{r setup,warning=FALSE,message=FALSE,cache=TRUE}
library(DURIAN)
data(c("C","B","pDataC"))
```

##### Preprocess the data
```{r, cache=TRUE}
library(Seurat)

seur = CreateSeuratObject(counts=C)
seur = NormalizeData(seur)
genes = VariableFeatures(FindVariableFeatures(seur, selection.method = "vst", nfeatures = 1500))
comgenes = intersect(genes,rownames(B))
C_prepro = DURIAN::subsetsc(scremoutlier(C),geneids=comgenes,return_obj=TRUE,nsd=3)
pDataC_prepro = pDataC[colnames(C_prepro),]
```

##### Run imputation on the single-cell data, using the bulk data for supervision.
```{r,warning=FALSE,message=FALSE,results='hide',cache = TRUE}
impresult_list=run_durian(
      scrabble_parameters = c(1,1e-6,1e-4),
      nEM = 5,
      scdata = C_prepro,
      metadata = pDataC_prepro,
      bulkdata = B,
      deconv_method = "MuSiC",
      nIter_outer = 3,
      nIter_inner = 3,
      nSDCIters = 50000,
      DECONVGENETHRESH=-0.01,
      SCRGENETHRESH=-0.01,
      outerStats = FALSE,
      durianEps=1e-3,
      saveImputationLog = FALSE,
      saveDeconvolutionLog = FALSE,
      saveImputedStep=FALSE)
  impresult = impresult_list[["C"]]
```

##### Construct a low-dimensional UMAP embedding from imputed and original data
```{r,warning=FALSE,message=FALSE,results='hide'}
library(umap)
library(ggplot2)
library(reshape2)
umap_imputed = umap(t(impresult))
umap_orig = umap(t(as.matrix(C_prepro)))
imputed_df = cbind(umap_imputed$layout,pDataC_prepro)
imputed_df$status = "Imputed"
orig_df = cbind(umap_orig$layout,pDataC_prepro)
orig_df$status = "Unimputed"
df = rbind(imputed_df,orig_df)
colnames(df) = c("UMAP1","UMAP2","cellID","cellType","sampleID","status")
df$status = factor(df$status,levels=c("Unimputed","Imputed"))
```

##### Plot the original and imputed data
```{r,warning=FALSE,message=FALSE,results='hide', fig.width=7,fig.height=3,dev = "svg",fig.ext="svg"}
ggplot(df,aes(x=UMAP1, y=UMAP2,color=cellType)) + 
      geom_point(size=1)+
      facet_grid(~status,scales="free") + theme_bw()
```


